var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/analytics/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__15c786cf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_bad9f0c8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__658c3d2b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf15385e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_analytics_page_actions_40c9bff0.js")
R.m(50949)
module.exports=R.m(50949).exports
